spring:
  application:
    name: Auth-Server
  config:
    import: optional:configserver:http://localhost:8888

jwt:
  secret: ecf1222c-88fd-47f3-988f-bdd78bade1ad

server:
  servlet:
    context-path: /api/v1/

